version: "3.8"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://sarbin:sarbin@db:5432/taskmanagement?schema=public # Updated DB URL
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install && npx prisma migrate deploy && npm run build && npm start" # Prisma migration added

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sarbin
      POSTGRES_PASSWORD: sarbin
      POSTGRES_DB: taskmanagement
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
